/**
 * PnlOpt.java
 */
package Presentacion;

import Dominio.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Galindo, Francisco Felix
 */
public class PnlOpt extends javax.swing.JPanel implements ComponenteSala {

    private Jugador jugador;
    private FrmSala sala;

    /**
     * Crea PnlOpt.
     */
    public PnlOpt(Jugador jugador, FrmSala sala) {
        initComponents();
        this.jugador = jugador;
        this.sala = sala;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();

        salir.setText("Salir al Menu Principal");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "¿Seguro que sea abandonar la partida?", "Abandono de partida", JOptionPane.YES_NO_OPTION);

        if (showConfirmDialog == JOptionPane.YES_OPTION) {
            jugador.setPuntaje(0);
            MenuInicial mi = MenuInicial.getInstance(jugador);
            mi.setVisible(true);
            this.sala.dispose();
        }
    }//GEN-LAST:event_salirActionPerformed

    @Override
    public void actualizar() {
        //funcionalidad por agregar
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
