/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Jugador;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Galindo
 */
public class MenuInicial extends javax.swing.JFrame {
    
    Jugador jugador;
    
    private static MenuInicial instance;

    /**
     * Creates new form MenuInicial
     */
    private MenuInicial(Jugador jugador) {
        initComponents();
        this.setResizable(false);
        this.setPreferredSize(new Dimension(580, 370));
        this.setLocationRelativeTo(null);
        this.setTitle("Timbiriche.");
        
        if(jugador == null){
            DlgRegistrarJugador pnlreg = new DlgRegistrarJugador(this, true);
            pnlreg.setVisible(true);
        }else{
            this.jugador = jugador;
        }
    }
    
    public static MenuInicial getInstance(Jugador jugador){
        if(instance == null){
            instance = new MenuInicial(jugador);
        }
        instance.jugador = jugador;
        return instance;
    }

    public Jugador getJugador() {
        return jugador;
    }

    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
        this.avatarIcon.setIcon(new ImageIcon("src\\Avatares\\" + jugador.getRutaAvatar()));
        this.nombreJugador.setText(jugador.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        unirPartida = new javax.swing.JButton();
        configurarTablero = new javax.swing.JButton();
        cerrarTimbiriche = new javax.swing.JButton();
        nombreJugador = new javax.swing.JLabel();
        avatarIcon = new javax.swing.JLabel();
        crearSala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        unirPartida.setText("Unirse a una sala");
        unirPartida.setMaximumSize(new java.awt.Dimension(180, 180));
        unirPartida.setMinimumSize(new java.awt.Dimension(180, 180));
        unirPartida.setPreferredSize(new java.awt.Dimension(180, 180));
        unirPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unirPartidaActionPerformed(evt);
            }
        });

        configurarTablero.setText("Configurar Tablero");
        configurarTablero.setMaximumSize(new java.awt.Dimension(180, 180));
        configurarTablero.setMinimumSize(new java.awt.Dimension(180, 180));
        configurarTablero.setPreferredSize(new java.awt.Dimension(180, 180));
        configurarTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurarTableroActionPerformed(evt);
            }
        });

        cerrarTimbiriche.setText("Cerrar Timbiriche");
        cerrarTimbiriche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarTimbiricheActionPerformed(evt);
            }
        });

        nombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        avatarIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        avatarIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        avatarIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        avatarIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        crearSala.setText("Crear sala");
        crearSala.setMaximumSize(new java.awt.Dimension(180, 180));
        crearSala.setMinimumSize(new java.awt.Dimension(180, 180));
        crearSala.setPreferredSize(new java.awt.Dimension(180, 180));
        crearSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(unirPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(crearSala, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(configurarTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avatarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarTimbiriche, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avatarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(configurarTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unirPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(cerrarTimbiriche)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unirPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unirPartidaActionPerformed
        JOptionPane.showMessageDialog(this, "Work in progress...", "WIP", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_unirPartidaActionPerformed

    private void configurarTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurarTableroActionPerformed
        FrmPreferencias conf = FrmPreferencias.getInstance(this);
        conf.setVisible(true);
    }//GEN-LAST:event_configurarTableroActionPerformed

    private void cerrarTimbiricheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarTimbiricheActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que quiere cerrar el juego?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_cerrarTimbiricheActionPerformed

    private void crearSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSalaActionPerformed
        FrmCreadorDeSala frmCreador = FrmCreadorDeSala.getInstance(jugador);
        this.dispose();
        frmCreador.setVisible(true);
    }//GEN-LAST:event_crearSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarIcon;
    private javax.swing.JButton cerrarTimbiriche;
    private javax.swing.JButton configurarTablero;
    private javax.swing.JButton crearSala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreJugador;
    private javax.swing.JButton unirPartida;
    // End of variables declaration//GEN-END:variables
}
