/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Alejandro Galindo
 */
public class pnlConfiguracionColores extends javax.swing.JPanel {

    /**
     * Creates new form panelConfiguracion
     */
    public pnlConfiguracionColores() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCuadro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        escogerColorCuadro = new javax.swing.JButton();
        panelLinea = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        escogerColorLinea = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(200, 221));
        setMinimumSize(new java.awt.Dimension(200, 221));

        jLabel1.setText("Color de Cuadro:");

        escogerColorCuadro.setText("Escoger color de cuadro");
        escogerColorCuadro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escogerColorCuadroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCuadroLayout = new javax.swing.GroupLayout(panelCuadro);
        panelCuadro.setLayout(panelCuadroLayout);
        panelCuadroLayout.setHorizontalGroup(
            panelCuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(escogerColorCuadro))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelCuadroLayout.setVerticalGroup(
            panelCuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escogerColorCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel3.setText("Color de linea:");

        escogerColorLinea.setText("Escoger color de linea");
        escogerColorLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escogerColorLineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLineaLayout = new javax.swing.GroupLayout(panelLinea);
        panelLinea.setLayout(panelLineaLayout);
        panelLineaLayout.setHorizontalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLineaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(escogerColorLinea))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLineaLayout.setVerticalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLineaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escogerColorLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void escogerColorLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escogerColorLineaActionPerformed
        Color color = JColorChooser.showDialog(this, "Escoge un color para la linea", Color.BLACK);
        if (color == null){
            color = Color.BLACK;
        }
        
        panelLinea.setBackground(color);
    }//GEN-LAST:event_escogerColorLineaActionPerformed

    private void escogerColorCuadroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escogerColorCuadroActionPerformed
        Color color = JColorChooser.showDialog(this, "Escoge un color para el cuadro", Color.BLACK);
        if (color == null){
            color = Color.BLACK;
        }
        
        panelCuadro.setBackground(color);
    }//GEN-LAST:event_escogerColorCuadroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton escogerColorCuadro;
    private javax.swing.JButton escogerColorLinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelCuadro;
    private javax.swing.JPanel panelLinea;
    // End of variables declaration//GEN-END:variables
}
