/**
 * PnlPreferencias.java
 */
package Presentacion;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JPanel;

/**
 *
 * @author Alejandro Galindo, Francisco Felix, Cesar Acactitla
 */
public class PnlPreferencias extends javax.swing.JPanel {

    /**
     * Crea panelConfiguracion
     */
    public PnlPreferencias(String color) {
        initComponents();
        this.panelColorEscogido.setBackground(Color.decode(color));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLinea = new javax.swing.JPanel();
        escogerColorLinea = new javax.swing.JButton();
        panelColorEscogido = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(200, 221));
        setMinimumSize(new java.awt.Dimension(200, 221));

        escogerColorLinea.setText("Escoger color de linea");
        escogerColorLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escogerColorLineaActionPerformed(evt);
            }
        });

        panelColorEscogido.setBackground(new java.awt.Color(0, 0, 0));
        panelColorEscogido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelColorEscogidoLayout = new javax.swing.GroupLayout(panelColorEscogido);
        panelColorEscogido.setLayout(panelColorEscogidoLayout);
        panelColorEscogidoLayout.setHorizontalGroup(
            panelColorEscogidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelColorEscogidoLayout.setVerticalGroup(
            panelColorEscogidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLineaLayout = new javax.swing.GroupLayout(panelLinea);
        panelLinea.setLayout(panelLineaLayout);
        panelLineaLayout.setHorizontalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLineaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelColorEscogido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escogerColorLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLineaLayout.setVerticalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLineaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escogerColorLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelColorEscogido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void escogerColorLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escogerColorLineaActionPerformed
        Color color = JColorChooser.showDialog(this, "Escoge un color para la linea", Color.BLACK);
        if (color == null){
            color = Color.BLACK;
        }
        
        this.panelColorEscogido.setBackground(color);
    }//GEN-LAST:event_escogerColorLineaActionPerformed

    /**
     * Regresa el color escogido.
     * @return 
     */
    public Color getColorEscogido() {
        return panelColorEscogido.getBackground();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton escogerColorLinea;
    private javax.swing.JPanel panelColorEscogido;
    private javax.swing.JPanel panelLinea;
    // End of variables declaration//GEN-END:variables
}
