/**
 * FrmPreferencias.java
 */
package presentacion.inicio;

import Dominio.Preferencia;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Alejandro Galindo, Francisco Felix
 */
public class FrmPreferencias extends javax.swing.JFrame {

    /**
     * Instancia de MenuInicial que lo invoca
     */
    private MenuInicial menu;

    /**
     * Instancia de preferencia que se va a crear
     */
    private Preferencia pref;

    /**
     * Coleccion de paneles de preferencias.
     */
    private List<PnlPreferencias> pnls = new ArrayList<>();

    /**
     * Instancia estatica y unica de si mismo.
     */
    private static FrmPreferencias instance;

    /**
     * Crea FrmPreferencias
     */
    private FrmPreferencias(MenuInicial menu) {
        this.menu = menu;
        initComponents();

        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Ajusta tus colores");

        PnlPreferencias pnlJugador = new PnlPreferencias(menu.getJugador().getColor());
        pnls.add(pnlJugador);
        tabbed.add(pnlJugador);
        tabbed.setTitleAt(0, "Tu");

        List<String> colores = menu.getJugador().getPreferencia().getColores();

        for (int i = 1; i <= colores.size(); i++) {
            PnlPreferencias pnl = new PnlPreferencias(colores.get(i-1));
            pnls.add(pnl);
            tabbed.add(pnl);
            tabbed.setTitleAt(i, "Jugador" + (i + 1));
        }
    }

    /**
     * Metodo estatico que regresa la unica instancia de FrmPreferencias. Si
     * esta instancia no ha sido creada, la crea.
     *
     * @param menu
     * @return
     */
    public static FrmPreferencias getInstance(MenuInicial menu) {
        if (instance == null) {
            instance = new FrmPreferencias(menu);
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        tabbed = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        guardar.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        guardar.setText("Guardar");
        guardar.setMaximumSize(new java.awt.Dimension(50, 100));
        guardar.setMinimumSize(new java.awt.Dimension(50, 100));
        guardar.setPreferredSize(new java.awt.Dimension(50, 100));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setMaximumSize(new java.awt.Dimension(50, 100));
        cancelar.setMinimumSize(new java.awt.Dimension(50, 100));
        cancelar.setPreferredSize(new java.awt.Dimension(50, 100));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        tabbed.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tabbed.setMaximumSize(new java.awt.Dimension(270, 270));
        tabbed.setMinimumSize(new java.awt.Dimension(270, 270));
        tabbed.setPreferredSize(new java.awt.Dimension(270, 270));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Guarda preferencias.
     *
     * @param evt
     */
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        //Codigo para que haga algo

        Color color = pnls.get(0).getColorEscogido();
        String colorHex1 = String.format("#%02x%02x%02x", color.getRed(), color.getGreen(), color.getBlue());
        color = pnls.get(1).getColorEscogido();
        String colorHex2 = String.format("#%02x%02x%02x", color.getRed(), color.getGreen(), color.getBlue());
        color = pnls.get(2).getColorEscogido();
        String colorHex3 = String.format("#%02x%02x%02x", color.getRed(), color.getGreen(), color.getBlue());
        color = pnls.get(3).getColorEscogido();
        String colorHex4 = String.format("#%02x%02x%02x", color.getRed(), color.getGreen(), color.getBlue());

        this.menu.getJugador().setColor(colorHex1);
        pref = new Preferencia(colorHex2, colorHex3, colorHex4);

        this.menu.getJugador().setPreferencia(pref);
        this.dispose();
    }//GEN-LAST:event_guardarActionPerformed

    /**
     * Cierra FrmPreferencias.
     *
     * @param evt
     */
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane tabbed;
    // End of variables declaration//GEN-END:variables
}
