/**
 * FrmCreadorDeSala.java
 */
package Presentacion;

import Dominio.Jugador;

/**
 *
 * @author Alejandro Galindo, Francisco Felix, Cesar Acactitla
 */
public class FrmCreadorDeSala extends javax.swing.JFrame {
    
    private static FrmCreadorDeSala instance;
    private Jugador jugador;
    private int tamanio;

    /**
     * Crea FrmCreadorSala
     */
    private FrmCreadorDeSala(Jugador jugador) {
        initComponents();
        this.setTitle("Tamaño de la sala");
        this.setLocationRelativeTo(null);
        this.jugador = jugador;
    }
    
    public static FrmCreadorDeSala getInstance(Jugador jugador){
        if(instance == null){
            instance = new FrmCreadorDeSala(jugador);
        }
        instance.jugador = jugador;
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dosButton = new javax.swing.JButton();
        tresButton = new javax.swing.JButton();
        cuatroButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dosButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dosButton.setText("2");
        dosButton.setMaximumSize(new java.awt.Dimension(120, 120));
        dosButton.setMinimumSize(new java.awt.Dimension(120, 120));
        dosButton.setPreferredSize(new java.awt.Dimension(120, 120));
        dosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosButtonActionPerformed(evt);
            }
        });

        tresButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tresButton.setText("3");
        tresButton.setMaximumSize(new java.awt.Dimension(120, 120));
        tresButton.setMinimumSize(new java.awt.Dimension(120, 120));
        tresButton.setPreferredSize(new java.awt.Dimension(120, 120));
        tresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresButtonActionPerformed(evt);
            }
        });

        cuatroButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cuatroButton.setText("4");
        cuatroButton.setMaximumSize(new java.awt.Dimension(120, 120));
        cuatroButton.setMinimumSize(new java.awt.Dimension(120, 120));
        cuatroButton.setPreferredSize(new java.awt.Dimension(120, 120));
        cuatroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Cuántos jugadores habrá en la sala?");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dosButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(tresButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cuatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dosButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tresButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        MenuInicial menuIn = MenuInicial.getInstance(jugador);
        menuIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void dosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosButtonActionPerformed
        this.tamanio = 2;
        crearSala();
    }//GEN-LAST:event_dosButtonActionPerformed

    private void tresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresButtonActionPerformed
        this.tamanio = 3;
        crearSala();
    }//GEN-LAST:event_tresButtonActionPerformed

    private void cuatroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroButtonActionPerformed
        this.tamanio = 4;
        crearSala();
    }//GEN-LAST:event_cuatroButtonActionPerformed

    private void crearSala(){
        FabricaSala fbrSala = new FabricaSala();
        FrmSala sala = (FrmSala) fbrSala.creaSala(jugador, tamanio);
        Thread tr = new Thread(sala);
        tr.start();
        sala.setVisible(true);
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cuatroButton;
    private javax.swing.JButton dosButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton tresButton;
    // End of variables declaration//GEN-END:variables
}